hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  httpclient:
    enabled: true

headers:
  client-version: X-CLIENT-VERSION

zuul:
  ignoredPatterns: /system/**,/login,/user
  routes:
    api:
      path: /api/**
      serviceId: bff
    integration:
      path: /products/**
      serviceId: product
      stripPrefix: false
  debug:
    request: true

security:
  oauth2:
    client:
      clientId: 7d51ac30432b58700d73
      clientSecret: f346050eddd93a5a5f65934fa096117bc05746af
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user

management:
  port: 4568
  context-path: /system
  security: false